export const tags = [
  { name: "Social", code: "SOC" },
  { name: "Mobilidade", code: "MOB" },
  { name: "Acessibilidade", code: "ACS" },
  { name: "Academia", code: "ACD" },
  { name: "Infraestrutura", code: "INF" },
  { name: "Reforma", code: "REF" },
  { name: "Financeiro", code: "FIN" },
  { name: "Atendimento", code: "ATD" },
  { name: "Elevador", code: "ELV" },
  { name: "Estacionamento", code: "EST" },
  { name: "Energia", code: "ENE" },
  { name: "Água", code: "AGU" },
  { name: "Segurança", code: "SEG" },
  { name: "Limpeza", code: "LMP" },
  { name: "Jardinagem", code: "JRD" },
  { name: "Piscina", code: "PSC" },
  { name: "Eventos", code: "EVT" },
  { name: "Manutenção", code: "MAN" },
  { name: "Internet/Wi-Fi", code: "NET" },
  { name: "Convivência", code: "CNV" },
  { name: "Barulho", code: "BRL" },
  { name: "Portaria", code: "PRT" },
  { name: "Correspondência", code: "COR" },
  { name: "CFTV", code: "CAM" },
  { name: "Gás", code: "GAS" },
  { name: "Iluminação", code: "ILU" },
  { name: "Áreas Comuns", code: "COM" },
  { name: "Conselho/Síndico", code: "ADM" },
];
